version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: gpon-db-server
    restart: always
    ports:
      - "27018:27017"
    environment:

      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      
    volumes:
      - gpon_mongodb_data:/data/db
    networks:
      - internal-net   # ✅ only internal

  nextjs:
    build: .
    container_name: gpon-dashboard
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      AUTH_SECRET: $AUTH_SECRET}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
      MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/{MMONGODB_DB_NAME}?authSource=admin
    depends_on:
      - mongodb
    networks:
      - internal-net
      - npm-net        # ✅ connect to NPM

volumes:
  gpon_mongodb_data:

networks:
  internal-net:
    driver: bridge

  npm-net:
    external: true
    name: nginx-pm_default   # ✅ existing NPM network