version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: gpon-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db

  nextjs:
    build: .
    container_name: gpon-next
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongodb

volumes:
  mongodb_data: